import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import html2canvas from 'html2canvas';
import './styles.css';

const platforms=['WhatsApp','Telegram','Instagram','Messenger','TXT / JSON'];
function App(){
 const [screen,setScreen]=useState('home'),[file,setFile]=useState(null),[text,setText]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[data,setData]=useState(null),[input,setInput]=useState(''),[messages,setMessages]=useState([]),[typing,setTyping]=useState(false);
 useEffect(()=>{const s=localStorage.getItem('cwex_session');if(s){try{const d=JSON.parse(s);setData(d);setScreen('chat')}catch{}}},[]);
 const analyze=async()=>{setError('');setLoading(true);try{const raw=file?await file.text():text;if(!raw.trim())throw Error('Please upload or paste a chat first.');const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chatText:raw})});const d=await r.json();if(!r.ok)throw Error(d.error||'Analysis failed.');setData(d);localStorage.setItem('cwex_session',JSON.stringify(d));setMessages([]);setScreen('chat')}catch(e){setError(e.message)}finally{setLoading(false)}};
 const send=async()=>{if(!input.trim()||typing)return;const u=input.trim();setInput('');setMessages(m=>[...m,{role:'user',content:u}]);setTyping(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:data.sessionId,ownerToken:data.ownerToken,message:u,history:messages})});const d=await r.json();if(!r.ok)throw Error(d.error||'Reply failed.');setTimeout(()=>{setMessages(m=>[...m,{role:'assistant',content:d.reply}]);setTyping(false)},500+Math.random()*1000)}catch(e){setMessages(m=>[...m,{role:'assistant',content:e.message}]);setTyping(false)}};
 const del=async()=>{if(!data)return;if(confirm('Delete this simulation and its saved profile?')){await fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:data.sessionId,ownerToken:data.ownerToken})});localStorage.removeItem('cwex_session');setData(null);setMessages([]);setScreen('home')}};
 const share=async()=>{const url=location.href;navigator.share?navigator.share({title:'ChatWithEx',text:'AI chat simulation',url}):navigator.clipboard.writeText(url).then(()=>alert('Link copied.'))};
 const saveImage=async()=>{const el=document.querySelector('.chat-card');const c=await html2canvas(el,{backgroundColor:'#fff'});const a=document.createElement('a');a.download='chatwithex.png';a.href=c.toDataURL();a.click()};
 if(screen==='home')return <main className="home"><img className="logo" src="/logo.png" onError={e=>e.currentTarget.style.display='none'} /><div className="hero"><p>Your historical chat is analyzed once to recreate their texting style.</p><button onClick={()=>setScreen('setup')}>Start Chat</button></div><div className="note">AI-generated simulation · Not the real person</div></main>;
 if(screen==='setup')return <main className="setup"><header><button className="back" onClick={()=>setScreen('home')}>←</button><div className="brand small">ChatWithEx</div></header><section className="panel"><h2>Create your simulation</h2><p className="muted">Choose a chat type, then upload your exported chat or paste it below.</p><div className="platforms">{platforms.map(x=><div className="platform" key={x}>{x}</div>)}</div><label className="upload">{file?file.name:'Upload chat file'}<input type="file" accept=".txt,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Or paste your chat here..."/><div className="privacy">Your raw chat is used for temporary analysis. The saved profile is compact and does not contain the original chat.</div>{error&&<div className="error">{error}</div>}<button className="primary" disabled={loading} onClick={analyze}>{loading?'Analyzing…':'Analyze & Start Chat'}</button></section></main>;
 return <main className="chat-page"><header className="chat-head"><button className="back" onClick={()=>setScreen('setup')}>←</button><div className="avatar">♥</div><div><div className="person">{data?.character||'ChatWithEx'}</div><div className="status">AI Simulation</div></div><div className="actions"><button onClick={share}>Share</button><button onClick={saveImage}>Save</button><button onClick={del}>Delete</button></div></header><section className="chat-card"><div className="disclosure">AI simulation based on historical chat · Not the actual person</div><div className="messages">{messages.length===0&&<div className="empty">Start the conversation.</div>}{messages.map((m,i)=><div key={i} className={'row '+m.role}><div className="bubble">{m.content}</div><span className="ticks">{m.role==='user'?'✓✓':' '}</span></div>)}{typing&&<div className="row assistant"><div className="bubble typing"><i/> <i/> <i/></div></div>}</div></section><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={'Message '+(data?.character||'them')+'…'}/><button onClick={send}>Send</button></div></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
